spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
server:
  port: 8060
  error:
    include-message: always
