spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/profile/**
          filters:
            - AuthFilter
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/v1/chats/**
          filters:
            - AuthFilter
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/v1/messages/**
          filters:
            - AuthFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
server:
  port: 8060
  error:
    include-message: always
