spring:
  application:
    name: zipkin-service

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8671/eureka

logging:
  level:
    org.springframework.web: debug

server:
  port: 9411
